# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 14:36
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20141202_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ['name'], 'verbose_name': 'Type of task', 'verbose_name_plural': 'Types of tasks'},
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_hours',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(24), django.core.validators.RegexValidator('^([0-9]{1,2}(\\.[05])?)$', 'Only .5 numbers')], verbose_name='total_hours'),
        ),
    ]
