---
  - name: Creating default group
    group:
      name={{relojito_default_group}}
      state=present

  - name: Creating default user
    user:
      name={{relojito_default_user}}
      groups={{relojito_default_group}}
      state=present
      createhome=no

  - name: Copying env vars
    template:
      src=relojito_vars.sh.j2
      dest=/etc/profile.d/relojito_vars.sh
      backup=no
    tags:
        - deploy

  - name: Adding remote user to default group
    user:
      name={{remote_user}}
      groups={{relojito_default_group}}
      append=yes

  - name: Adding nginx user to default group
    user:
      name=www-data
      groups={{relojito_default_group}}
      append=yes

  - name: Adding additional dirs
    file:
      path={{item}}
      state=directory
      mode=770
      owner={{relojito_default_user}}
      group={{relojito_default_group}}
    with_items:
      - "{{relojito_virtualenv_dir}}"
      - "{{relojito_log_dir}}"
      - "{{relojito_log_dir}}/celery"
      - "{{relojito_log_dir}}/django"
      - "{{relojito_log_dir}}/supervisor"
      - "{{relojito_log_dir}}/uwsgi"

  - name: Creating main directory
    file:
      path={{relojito_main_dir}}
      state=directory
      mode=770
      owner={{remote_user}}
      group={{relojito_default_group}}
    when: remote_vm

  - name: Main directory rsync
    synchronize:
        dest=/opt
        src={{relojito_main_dir}}
        copy_links=yes
        recursive=yes
        delete=yes
        rsync_opts=--no-motd,--include-from=/opt/relojito_project/provisioning/roles/relojito/files/rsync_filter
    become: no
    when: remote_vm
    tags:
        - deploy
        - rsync

  - name: sigel | Deleting pyc files
    shell: "find . -name '*.pyc' -delete"
    args:
      chdir: "{{relojito_main_dir}}"
    tags:
      - deploy

  - name: Creating Django log file
    file:
      path={{relojito_log_file}}
      state=touch
      owner={{relojito_default_user}}
      group={{relojito_default_group}}
      mode=664

  - name: Adding venv symlink to home
    file:
      dest=/home/{{remote_user}}/Envs/{{relojito_virtualenv_name}}
      src={{relojito_virtualenv_dir}}
      state=link

  - name: Installing apt packages
    apt:
      name={{item}}
      state=present
    with_items:
      - libjpeg-dev
      - gettext
      - fortune

  - name: Altering venv directory permissions
    file:
      mode="g=rwX"
      state=directory
      recurse=yes
      path={{relojito_virtualenv_dir}}
      owner={{relojito_default_user}}
      group={{relojito_default_group}}
    tags:
      - deploy

  - name: Installing base requirements
    pip:
      requirements={{relojito_requirements}}
      virtualenv={{relojito_virtualenv_dir}}
      virtualenv_python=python3
    become_user: "{{relojito_default_user}}"
    tags:
      - requirements

  - name: Installing development requirements
    pip:
      requirements={{relojito_requirements_dev}}
      virtualenv={{relojito_virtualenv_dir}}
    become_user: "{{relojito_default_user}}"
    tags:
      - requirements

  - name: Copying celery configuration template
    template:
      src=celery_config.py.j2
      dest={{relojito_main_dir}}/relojito/relojito/celery.py
      backup=no
    tags:
      - deploy

  - name: Copying development configuration template
    template:
      src=settings_development.j2
      dest={{relojito_main_dir}}/relojito/relojito/settings/development.py
      backup=no
    when: relojito_environment == 'development'
    tags:
      - deploy

  - name: Copying staging configuration template
    template:
      src=settings_staging.j2
      dest={{relojito_main_dir}}/relojito/relojito/settings/staging.py
      backup=no
    when: relojito_environment == 'staging'
    tags:
      - deploy

  - name: Copying production configuration template
    template:
      src=settings_production.j2
      dest={{relojito_main_dir}}/relojito/relojito/settings/production.py
      backup=no
    when: relojito_environment == 'production'
    tags:
      - deploy

  - name: Restarting PostgreSQL to kill connections
    service:
      name=postgresql
      state=restarted
    when: recreate_db == 'yes' and relojito_environment == 'development'

  - name: Removing existing DB
    shell:
      dropdb {{relojito_dbname}}
    become: yes
    become_user: postgres
    when: recreate_db == 'yes' and relojito_environment == 'development'

  - name: Creating DB
    shell: createdb {{relojito_dbname}}
    become: yes
    become_user: postgres
    when: recreate_db == 'yes' and relojito_environment == 'development'

  - name: Copying uwsgi configuration
    template:
      src=relojito_uwsgi.ini.j2
      dest=/etc/uwsgi/apps_available/relojito_uwsgi.ini
      backup=yes

  - name: Activating app in uWSGI emperor
    file:
      src=/etc/uwsgi/apps_available/relojito_uwsgi.ini
      dest=/etc/uwsgi/apps_enabled/relojito_uwsgi.ini
      state=link

  - name: Copying systemd celery unit template
    template:
      src=celery_relojito.service.j2
      dest=/etc/systemd/system/celery_relojito.service
    tags:
      - deploy

  - name: Enabling systemd celery service
    service:
      name=celery_relojito.service
      enabled=yes
    tags:
      - deploy

  - name: Copying systemd uwsgi unit template
    template:
      src=uwsgi.service.j2
      dest=/etc/systemd/system/uwsgi.service
    tags:
      - deploy

  - name: Enabling systemd uwsgi service
    service:
      name=uwsgi.service
      enabled=yes
    tags:
      - deploy

  - name: Restarting uWSGI
    service:
      name=uwsgi
      state=restarted
    tags:
      - restart

  - name: Copying configuration for nginx
    template:
      src=relojito_nginx.j2
      dest=/etc/nginx/sites-available/relojito_nginx
      backup=yes
    tags:
      - deploy

  - name: Collecting static files
    django_manage:
      command=collectstatic
      virtualenv={{relojito_virtualenv_dir}}
      settings=relojito.settings.{{relojito_environment}}
      app_path={{relojito_main_dir}}/relojito
    tags:
      - deploy

  - name: Disabling default site in nginx
    file:
      path=/etc/nginx/sites-enabled/default
      state=absent

  - name: Activating site in nginx
    file:
      src=/etc/nginx/sites-available/relojito_nginx
      dest=/etc/nginx/sites-enabled/relojito_nginx
      state=link
    notify:
      - restart nginx

  - name: Restarting nginx
    service:
      name=nginx
      state=restarted
    tags:
      - restart
